

spring:

  # redis:
    # host: 127.0.0.1
    # password:
    # port: 6379

  data:
    mongodb:
      host: 127.0.0.1
      database: postoffice
      username: postoffice
      password: postoffice

    redis:
      host: 127.0.0.1
      # password:
      port: 6379

      redis:
        password: myredis2018
        host: 127.0.0.1

security:
  auth:
    serverBaseURL: http://127.0.0.1:8080
    getUserByTokenURL: ${security.auth.serverBaseURL}/microprogram/getloginOnUser
    validateTokenURL: ${security.auth.serverBaseURL}/microprogram/token/validate


server:
  port: 9090